/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:15:28 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Book;
import ir.ramtung.impl1.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      boolean boolean0 = reference0.isTitled((String) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      String string0 = reference0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference("Documents with empty title are not allowed");
      reference0.title = "Documents with empty title are not allowed";
      reference0.title = "";
      String string0 = reference0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Book book0 = null;
      try {
        book0 = new Book("");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Documents with empty title are not allowed
         //
         verifyException("ir.ramtung.impl1.Document", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Reference reference0 = new Reference("3mO(r+hsfpDWBOVd#O");
      boolean boolean0 = reference0.isTitled("ir.ramtung.impl1.Magazine");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Reference reference0 = new Reference("3mO(r+hsfpDWBOVd#O");
      String string0 = reference0.getTitle();
      assertEquals("3mO(r+hsfpDWBOVd#O", string0);
  }
}
