/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:15:22 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Member;
import ir.ramtung.impl1.Professor;
import ir.ramtung.impl1.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Professor professor0 = new Professor((String) null);
      professor0.penalize(1194);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Professor professor0 = new Professor((String) null);
      Student student0 = new Student(" ", " ");
      boolean boolean0 = professor0.sameAs(student0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Student student0 = new Student(" ", " ");
      boolean boolean0 = student0.isNamed(" ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Student student0 = new Student("9-3uY;WtPhD}Rnh", "9-3uY;WtPhD}Rnh");
      student0.prevPenalty = 1579;
      int int0 = student0.getPrevPenalty();
      assertEquals(1579, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Professor professor0 = new Professor("7&Qn");
      professor0.prevPenalty = 0;
      professor0.prevPenalty = (-3545);
      int int0 = professor0.getPrevPenalty();
      assertEquals((-3545), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Professor professor0 = new Professor("ze_%omESASVH(@P");
      // Undeclared exception!
      try { 
        professor0.sameAs((Member) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Student student0 = null;
      try {
        student0 = new Student("", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Empty member name not allowed
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Professor professor0 = new Professor("ze_%omESASVH(@P");
      int int0 = professor0.getPrevPenalty();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Professor professor0 = new Professor("lGQ-,^wM]E&PSO@y");
      Student student0 = new Student("lGQ-,^wM]E&PSO@y", "lGQ-,^wM]E&PSO@y");
      boolean boolean0 = student0.sameAs(professor0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Professor professor0 = new Professor("7&Qn");
      boolean boolean0 = professor0.isNamed("T&Nl(v");
      assertFalse(boolean0);
  }
}
