/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:11:47 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("-FyT=),=CKEQ>g~ao", 1, 1);
      int int0 = magazine0.penaltyFor((-1655));
      assertEquals((-3310000), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("ir.ramtung.impl1.InvalidArgumentEx", 1390, 1390);
      int int0 = magazine0.penaltyFor(1);
      assertEquals(3000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("ir.ramtung.impl1.Document", 1505, 1505);
      int int0 = magazine0.penaltyFor(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = new Magazine("o9$R%", 1861, 1861);
      magazine0.year = 2;
      int int0 = magazine0.penaltyFor(2);
      assertEquals(4000, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("2NMk8A|&uGT`y/2(", 1, (-644));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative number
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("]", (-7), (-7));
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Magazine with zero or negative publication year
         //
         verifyException("ir.ramtung.impl1.Magazine", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Magazine magazine0 = new Magazine("o9$R%", 1861, 1861);
      int int0 = magazine0.loanDuration();
      assertEquals(2, int0);
  }
}
