/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:07:15 GMT 2024
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl1.Library;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addBook("]G", 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 3);
      library0.addProfMember("The document is not in member's loan");
      library0.borrow("The document is not in member's loan", (String) null);
      library0.returnDocument("The document is not in member's loan", (String) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.extend("aIl:/k, w9J", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addMagazine("w?XExUEsi", 1772, 1026, (-2872));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Library library0 = new Library();
      library0.addMagazine("=1Et", 3, 3, 3);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Library library0 = new Library();
      library0.addStudentMember("BP#xZ7sF\"n@d[^%Ip", "BP#xZ7sF\"n@d[^%Ip");
      try { 
        library0.addProfMember("BP#xZ7sF\"n@d[^%Ip");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Member with the same name exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      try { 
        library0.addBook("@!<!JRZm|a[*)eAnqzJs", 1648);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document with the same title exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.addReference((String) null, (-1));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Negative or zero copies of a document cannot be added
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("z5LOo<");
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      library0.borrow("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      library0.borrow("z5LOo<", "@!<!JRZm|a[*)eAnqzJs");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 2);
      library0.addProfMember((String) null);
      library0.borrow((String) null, (String) null);
      try { 
        library0.returnDocument((String) null, "z+xg|7UWBc#w7^>b&");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "?\"-sgX?r");
      library0.borrow("?\"-sgX?r", "@!<!JRZm|a[*)eAnqzJs");
      try { 
        library0.extend("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // The document is not in member's loan
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "?\"-sgX?r");
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      library0.borrow("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      int int0 = library0.getTotalPenalty("?\"-sgX?r");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 2);
      library0.addProfMember((String) null);
      library0.borrow((String) null, (String) null);
      int int0 = library0.getTotalPenalty((String) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.timePass((-1));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot go back in time
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Library library0 = new Library();
      library0.timePass(1648);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.getTotalPenalty("^}&Os%$Tf`'oPY");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      library0.borrow("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      try { 
        library0.extend("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot extend on the same day borrowed
         //
         verifyException("ir.ramtung.impl1.Loan", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference((String) null, 2);
      library0.addProfMember((String) null);
      library0.borrow((String) null, (String) null);
      library0.borrow((String) null, (String) null);
      List<String> list0 = library0.availableTitles();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1648);
      List<String> list0 = library0.availableTitles();
      assertTrue(list0.contains("@!<!JRZm|a[*)eAnqzJs"));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("u `l`%", 3);
      library0.addStudentMember("u `l`%", "u `l`%");
      library0.borrow("u `l`%", "u `l`%");
      library0.borrow("u `l`%", "u `l`%");
      try { 
        library0.borrow("u `l`%", "u `l`%");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot borrow more documents
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Library library0 = new Library();
      library0.addReference("@!<!JRZm|a[*)eAnqzJs", 1);
      library0.addStudentMember("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      library0.borrow("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
      try { 
        library0.borrow("@!<!JRZm|a[*)eAnqzJs", "@!<!JRZm|a[*)eAnqzJs");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Document is not available to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Library library0 = new Library();
      library0.addBook("2m%1?`Grgh'z\"u5", 41982);
      try { 
        library0.borrow("2m%1?`Grgh'z\"u5", "2m%1?`Grgh'z\"u5");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find member to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Library library0 = new Library();
      try { 
        library0.borrow("9LLA$i9_-oPc7Kliy", "9LLA$i9_-oPc7Kliy");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot find document to borrow
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Library library0 = new Library();
      library0.addProfMember("OY7` = f&%");
      try { 
        library0.addStudentMember("OY7` = f&%", "OY7` = f&%");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Member with the same name exists
         //
         verifyException("ir.ramtung.impl1.Library", e);
      }
  }
}
