/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:18:51 GMT 2024
 */

package ir.ramtung.sts01;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.sts01.Main;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Main main0 = new Main();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Main.main(stringArray0);
      assertEquals(1, stringArray0.length);
  }
}
