/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:19:28 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Magazine;
import ir.ramtung.impl2.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Reference reference0 = new Reference((String) null, 718);
      reference0.getTitle();
      assertEquals(718, reference0.getCopies());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Magazine magazine0 = new Magazine("", 0, 0, 0);
      String string0 = magazine0.getTitle();
      assertNotNull(string0);
      assertEquals(0, magazine0.getCopies());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Book book0 = new Book("\"", 564);
      book0.day = 0;
      int int0 = book0.getDay();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Book book0 = new Book("", 0);
      book0.day = (-1634);
      int int0 = book0.getDay();
      assertEquals((-1634), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Magazine magazine0 = new Magazine("?c", 0, (-177), 0);
      int int0 = magazine0.getCopies();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Book book0 = new Book("", 0);
      book0.barrowBook();
      int int0 = book0.getCopies();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Book book0 = new Book("", 0);
      book0.calculatePenalty((-1315));
      assertEquals(0, book0.getCopies());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Book book0 = new Book("}V'e-k*4lX'IN$eu", 5);
      int int0 = book0.getCopies();
      assertEquals(5, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Book book0 = new Book("}V'e-k*4lX'IN$eu", 5);
      book0.returnBook();
      assertEquals(6, book0.getCopies());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Reference reference0 = new Reference("}V'e-k*4lX'IN$eu", 10);
      String string0 = reference0.getTitle();
      assertEquals(10, reference0.getCopies());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Reference reference0 = new Reference("}V'e-k*4lX'IN$eu", 10);
      int int0 = reference0.getDay();
      assertEquals(10, reference0.getCopies());
      assertEquals(5, int0);
  }
}
