/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:16:59 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("Wxp*>eX,JZjp]7", 1390, 1390, (-1606));
      int int0 = magazine0.calculatePenalty(559);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("P;{G5|p\"zGi", (-1047), (-1), (-1));
      int int0 = magazine0.calculatePenalty((-1));
      assertEquals(2, magazine0.getDay());
      assertEquals(2000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("Q1;@", 1990, 1990, 1990);
      int int0 = magazine0.calculatePenalty(1990);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }
}
