/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:16:13 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Reference_ESTest extends Reference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("g", (-3119));
      int int0 = reference0.calculatePenalty(7000);
      assertEquals(5, reference0.getDay());
      assertEquals(5000, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("g", (-3119));
      int int0 = reference0.calculatePenalty((-3119));
      assertEquals(7000, int0);
      assertEquals(5, reference0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference("I$^!Y0<;5nk+}o-^V", (-809));
      int int0 = reference0.calculatePenalty((-3));
      assertEquals(5000, int0);
      assertEquals(5, reference0.getDay());
  }
}
