/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 12 20:17:08 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl2.Book;
import ir.ramtung.impl2.Document;
import ir.ramtung.impl2.Magazine;
import ir.ramtung.impl2.Prof;
import java.util.ArrayList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Prof_ESTest extends Prof_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Prof prof0 = new Prof("ia+iy\"Gkath|\"5@");
      ArrayList<Document> arrayList0 = new ArrayList<Document>();
      Book book0 = new Book("", (-1204));
      arrayList0.add((Document) book0);
      prof0.docsBorrow = (List<Document>) arrayList0;
      Magazine magazine0 = new Magazine("ia+iy\"Gkath|\"5@", (-1204), (-1204), (-1204));
      arrayList0.add((Document) magazine0);
      arrayList0.add((Document) book0);
      prof0.borrow(magazine0);
      assertTrue(prof0.canBorrow());
      
      arrayList0.add((Document) book0);
      arrayList0.add((Document) magazine0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Prof prof0 = new Prof("kcy5I#$\"Ib{B^");
      prof0.docsBorrow = null;
      // Undeclared exception!
      try { 
        prof0.canBorrow();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl2.Prof", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Prof prof0 = new Prof("ia+iy\"Gkath|\"5@");
      boolean boolean0 = prof0.canBorrow();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Prof prof0 = new Prof("ia+iy\"Gkath|\"5@");
      ArrayList<Document> arrayList0 = new ArrayList<Document>();
      Book book0 = new Book("", (-1204));
      arrayList0.add((Document) book0);
      prof0.docsBorrow = (List<Document>) arrayList0;
      Magazine magazine0 = new Magazine("ia+iy\"Gkath|\"5@", (-1204), (-1204), (-1204));
      arrayList0.add((Document) magazine0);
      arrayList0.add((Document) book0);
      prof0.borrow(magazine0);
      assertTrue(prof0.canBorrow());
      
      arrayList0.add((Document) book0);
      boolean boolean0 = prof0.canBorrow();
      assertFalse(boolean0);
  }
}
