/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jun 12 20:10:43 GMT 2024
 */

package ir.ramtung.impl2;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Person_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "ir.ramtung.impl2.Person"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
    Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("file.encoding", "UTF-8");
    System.setProperty("java.awt.headless", "true");
    System.setProperty("java.io.tmpdir", "/tmp");
    System.setProperty("user.country", "US");
    System.setProperty("user.dir", "/home/marzieh/Desktop/Files/Courses/CA3/junit-quickcheck");
    System.setProperty("user.home", "/home/marzieh");
    System.setProperty("user.language", "en");
    System.setProperty("user.name", "marzieh");
    System.setProperty("user.timezone", "");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Person_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.hash.HashCode$LongHashCode",
      "com.google.common.collect.AllEqualOrdering",
      "com.google.common.primitives.Longs$LongConverter",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.math.LongMath$1",
      "com.google.common.hash.Striped64$1",
      "com.google.common.hash.Murmur3_128HashFunction$Murmur3_128Hasher",
      "com.google.common.hash.BloomFilter$Strategy",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.hash.BloomFilterStrategies$1",
      "com.google.common.hash.BloomFilterStrategies$2",
      "com.google.common.collect.NullsLastOrdering",
      "com.google.common.primitives.Longs",
      "ir.ramtung.impl2.Person",
      "com.google.common.math.DoubleMath$1",
      "com.google.common.base.Converter$IdentityConverter",
      "com.google.common.collect.Range",
      "com.google.common.collect.ByFunctionOrdering",
      "com.google.common.hash.Funnel",
      "ir.ramtung.impl2.Document",
      "com.google.common.base.Predicate",
      "com.google.common.collect.LexicographicalOrdering",
      "ir.ramtung.impl2.Prof",
      "ir.ramtung.sts01.LibraryException",
      "com.google.common.hash.Striped64",
      "com.google.common.collect.NullsFirstOrdering",
      "com.google.common.collect.ImmutableAsList",
      "com.google.common.collect.DiscreteDomain$BigIntegerDomain",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.base.Strings",
      "com.google.common.math.MathPreconditions",
      "com.google.common.collect.DiscreteDomain",
      "com.google.common.collect.UsingToStringOrdering",
      "com.google.common.collect.UnmodifiableListIterator",
      "ir.ramtung.impl2.Student",
      "com.google.common.hash.PrimitiveSink",
      "com.google.common.hash.Hasher",
      "com.google.common.collect.Cut",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.math.DoubleUtils",
      "com.google.common.hash.HashCode",
      "com.google.common.collect.ImmutableList$1",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.hash.LongAddables$1",
      "com.google.common.base.Converter$ConverterComposition",
      "ir.ramtung.impl2.Book",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.hash.BloomFilterStrategies",
      "com.google.errorprone.annotations.Immutable",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.errorprone.annotations.DoNotMock",
      "com.google.common.base.Converter",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.hash.AbstractStreamingHasher",
      "com.google.common.base.Function",
      "com.google.common.collect.ComparatorOrdering",
      "com.google.common.collect.DiscreteDomain$IntegerDomain",
      "com.google.common.collect.AbstractIndexedListIterator",
      "ir.ramtung.impl2.Reference",
      "com.google.common.math.LongMath",
      "com.google.common.primitives.Ints$IntConverter",
      "com.google.common.hash.AbstractHasher",
      "com.google.common.collect.DiscreteDomain$LongDomain",
      "com.google.common.base.Converter$ReverseConverter",
      "com.google.common.collect.BoundType",
      "com.google.common.collect.ExplicitOrdering",
      "ir.ramtung.impl2.Magazine",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.hash.HashFunction",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.primitives.Booleans",
      "com.google.common.hash.LongAdder",
      "com.google.common.collect.Range$1",
      "com.google.common.base.Supplier",
      "com.google.common.hash.LongAddable",
      "com.google.common.hash.Hashing",
      "com.google.common.collect.CompoundOrdering",
      "com.google.common.hash.Striped64$Cell",
      "com.google.common.hash.AbstractHashFunction",
      "com.google.common.hash.Murmur3_128HashFunction",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.ReverseOrdering",
      "com.google.common.collect.Ordering$IncomparableValueException",
      "com.google.common.hash.BloomFilterStrategies$LockFreeBitArray",
      "com.google.common.hash.LongAddables",
      "com.google.common.math.DoubleMath",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.hash.BloomFilter",
      "com.google.common.collect.ReverseNaturalOrdering",
      "com.google.common.primitives.Ints",
      "com.google.common.hash.HashCode$IntHashCode",
      "com.google.common.hash.HashCode$BytesHashCode",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.Cut$AboveAll"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Person_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "ir.ramtung.impl2.Person",
      "ir.ramtung.impl2.Student",
      "ir.ramtung.impl2.Prof",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.Cut",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.collect.Cut$AboveAll",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.Range",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.primitives.Booleans",
      "ir.ramtung.impl2.Document",
      "ir.ramtung.impl2.Book",
      "ir.ramtung.impl2.Magazine",
      "ir.ramtung.sts01.LibraryException",
      "ir.ramtung.impl2.Reference",
      "com.google.common.hash.BloomFilter",
      "com.google.common.hash.BloomFilterStrategies",
      "com.google.common.base.Strings",
      "com.google.common.hash.BloomFilterStrategies$LockFreeBitArray",
      "com.google.common.math.LongMath",
      "com.google.common.math.LongMath$1",
      "com.google.common.primitives.IntsMethodsForWeb",
      "com.google.common.primitives.Ints",
      "com.google.common.hash.Striped64$1",
      "com.google.common.hash.Striped64",
      "com.google.common.hash.LongAdder",
      "com.google.common.hash.LongAddables$1",
      "com.google.common.hash.LongAddables",
      "com.google.common.hash.Hashing",
      "com.google.common.hash.AbstractHashFunction",
      "com.google.common.hash.Murmur3_128HashFunction",
      "com.google.common.hash.AbstractHasher",
      "com.google.common.hash.AbstractStreamingHasher",
      "com.google.common.hash.Murmur3_128HashFunction$Murmur3_128Hasher",
      "com.google.common.hash.HashCode",
      "com.google.common.hash.HashCode$BytesHashCode",
      "com.google.common.primitives.Longs",
      "com.google.common.base.Converter",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.base.Converter$IdentityConverter",
      "com.google.common.base.Converter$ConverterComposition",
      "com.google.common.collect.Range$1",
      "com.google.common.math.DoubleMath",
      "com.google.common.math.DoubleUtils",
      "com.google.common.math.DoubleMath$1",
      "com.google.common.math.MathPreconditions"
    );
  }
}
